guage: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
d
cache:
       pip:true
       apt:true
directories:
             - "~/.platformio"
env:
- PLATFORMIO_CI_SRC=.

install:
        sudo  pip install -U platformio
script:
         - mkdir build
         - cd build
         - cmake  ../ 
         - cd ..
         - platformio ci --board=uno
